################################################################################
# Makefile for Simplified Conv2D Test  (single-rounding / SR1 only)
#
#   make comp                 build test_conv2d_sr1  (TFLITE_SINGLE_ROUNDING=1)
#   make run                  build + run on the ISS
#   make clean
#
# RTL_DIAG=1 links the reftb + local-memory LSP for RTL/ISS bring-up.
################################################################################
RTL_DIAG ?= 0
LDFLAGS  ?=

ifeq ($(RTL_DIAG),1)
LDFLAGS += -lreftb -mlsp=min-rt-local_20260521_verilog_ok
endif

XTCC  ?= xt-clang
XTRUN ?= xt-run

NNLIB_BASE ?= ../../NW/TFLM/dsp/tflm/tflite-micro/tensorflow/lite/micro/tools/make/downloads/xa_nnlib_hifi5

NNLIB_INC = -I$(NNLIB_BASE)/include \
            -I$(NNLIB_BASE)/include/nnlib \
            -I$(NNLIB_BASE)/algo/common/include \
            -I$(NNLIB_BASE)/algo/kernels/cnn/hifi5 \
            -I$(NNLIB_BASE)/algo/ndsp/hifi5/include

CFLAGS = -g -O2 -Wall -Wno-unused-parameter $(NNLIB_INC) \
         -DXCHAL_HAVE_HIFI5 -DNDEBUG -D__XTENSA__ -DMODEL_INT16 -DNNLIB_V2 -Dhifi5 \
         -DTFLITE_SINGLE_ROUNDING=1

NNLIB_SRCS = $(NNLIB_BASE)/algo/kernels/cnn/hifi5/xa_nn_conv2d_std_sym8sxasym8s.orig.c \
             $(NNLIB_BASE)/algo/kernels/cnn/hifi5/xa_nn_matXvec_sym8sxasym8s_asym8s_circ.orig.c \
             $(NNLIB_BASE)/algo/kernels/cnn/hifi5/xa_nn_conv2d_std_circ_buf.c \
             $(NNLIB_BASE)/algo/kernels/cnn/hifi5/xa_nn_conv2d_depthwise.c \
             $(NNLIB_BASE)/algo/kernels/cnn/hifi5/xa_nn_circ_buf.c \
             $(NNLIB_BASE)/algo/kernels/matXvec/hifi5/xa_nn_matmul_8x8.c \
             $(NNLIB_BASE)/algo/kernels/matXvec/hifi5/xa_nn_matmul_asym8xasym8.c \
             $(NNLIB_BASE)/algo/kernels/basic/hifi5/xa_nn_memmove.c \
             $(NNLIB_BASE)/algo/common/src/xa_nnlib_common_api.c

TEST_NAME ?= test_conv2d_simple_0
TARGET    ?= test_conv2d_sr1
BUILD_DIR  = build_sr1

OBJS = $(BUILD_DIR)/$(TEST_NAME).o $(addprefix $(BUILD_DIR)/,$(notdir $(NNLIB_SRCS:.c=.o)))

# let make find NNLIB sources (and the local test .c) by filename
vpath %.c $(sort $(dir $(NNLIB_SRCS))) .

.PHONY: all comp run clean help
all: comp

comp: $(TARGET)
	@echo ">>> Built: $(TARGET) (TFLITE_SINGLE_ROUNDING=1)"

$(BUILD_DIR):
	mkdir -p $@

$(BUILD_DIR)/%.o: %.c | $(BUILD_DIR)
	@echo "  [CC] $(notdir $<)"
	$(XTCC) $(CFLAGS) -c $< -o $@

$(TARGET): $(OBJS)
	@echo ">>> Linking $@ ..."
	$(XTCC) $(CFLAGS) $(LDFLAGS) -o $@ $^

run: comp
	$(XTRUN) ./$(TARGET)

clean:
	rm -rf $(BUILD_DIR) $(TARGET) *.log
	@echo ">>> Clean done"

help:
	@echo "Usage: make comp | run | clean   [RTL_DIAG=1]"
