/*******************************************************************************
 * activation_cmodel.c
 *
 * C reference model for xa_nn_activations_asym8_asym8.
 *
 * Implements the bit-exact, gcc-verifiable subset of the asym8->asym8
 * activation family: generic clamp (covers ReLU / ReLU6 / arbitrary bounds).
 *
 * The quantized clamp is defined as:
 *   out[i] = clamp(inp[i], activation_min, activation_max)
 *
 * This is exact (integer comparison only) and fully verifiable with gcc.
 *
 * NOTE: There is NO MAC and NO partial_sum in this op.  The .in_out fixture
 *       format omits kernel, bias, out_multiplier, out_shift, and partial_sum.
 *
 * Zero-bias caller convention (consistent with conv2d cmodel and NNLib):
 *   input_zero_bias  = -input_zero_point   (added to each element before clamp)
 *   output_zero_bias = +output_zero_point  (added after clamp)
 * For a simple elementwise clamp where input and output share the same
 * quantization scale/zero-point (the common inference case), the zero-points
 * cancel and the net operation is a plain int8 clamp.  Fixtures that use
 * differing input/output zero-points are NOT in scope for the bit-exact subset
 * (they would require a requantize step), so all patterns here keep input and
 * output on the same scale (zero-points both 0, or both equal).
 *
 * ─────────────────────────────────────────────────────────────────────────────
 * STUB NOTICE — Sigmoid / Tanh
 * ─────────────────────────────────────────────────────────────────────────────
 * Sigmoid and Tanh over asym8 tensors require a 256-entry LUT generated by
 * the NNLib calibration flow (xa_nn_elm_sigmoid_asym8s_asym8s, etc.).
 * That LUT is not available in a pure-gcc environment and its values are
 * architecture-specific (fixed-point polynomial approximations tuned for
 * HiFi5).  These ops are therefore NOT implemented here and are out of scope
 * for gcc-verifiable testing.  If you add them in the future, mark every
 * PASS from this harness as CAVEAT: not bit-exact vs. NNLib.
 * ─────────────────────────────────────────────────────────────────────────────
 *
 * Requant core functions are copied verbatim from conv2d_std_cim_cmodel.c so
 * the arithmetic matches exactly.  They are compiled but unused in this file
 * (the pure clamp path needs no requantize); they are retained here for
 * completeness in case a future activation variant (e.g. requantizing clamp
 * across different scales) reuses them.
 ******************************************************************************/

#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>
#include <limits.h>

#include "activation_cmodel.h"

/* =========================================================================
 * Bit-exact requant core — copied verbatim from conv2d_std_cim_cmodel.c
 * (unused by the pure clamp path; retained for future requantizing variants)
 * ========================================================================= */

typedef union {
    int64_t long_long;
    struct {
        uint32_t low;
        int32_t  high;
    } word;
} nn_long_long;

/*
 * nn_divide_by_power_of_two
 * shift_change variant: exponent > 0 → left-shift, exponent <= 0 → right-shift.
 */
static inline int64_t nn_divide_by_power_of_two(int32_t dividend, int32_t exponent)
{
    int64_t result = 0;

    if (exponent <= 0) {                /* exponent < 0 → right shift */
        exponent = -exponent;
        const int32_t remainder_mask = (1 << exponent) - 1;
        int32_t remainder = remainder_mask & dividend;

        result = dividend >> exponent;

        int32_t threshold = remainder_mask >> 1;
        if (result < 0)
            threshold++;

        if (remainder > threshold)
            result++;
    } else {                            /* exponent > 0 → left shift */
        result = dividend * (1LL << exponent);
    }

    return result;
}

/*
 * nn_doubling_high_mult_no_sat
 * Computes (int32_t)((m1 * m2) >> 31) using a 64-bit union.
 */
static inline int32_t nn_doubling_high_mult_no_sat(int32_t m1, int32_t m2)
{
    int32_t    result = 0;
    nn_long_long mult;

    mult.word.low  = 0;
    mult.word.high = 0;

    mult.long_long = mult.long_long + (int64_t)m1 * m2;

    result = (int32_t)(mult.long_long >> 31);

    return result;
}

/*
 * nn_requantize — shift_change variant
 * Marked __attribute__((unused)) because the pure clamp path in this file
 * does not call it.  It is retained verbatim from conv2d_std_cim_cmodel.c
 * for future requantizing activation variants.
 */
static inline __attribute__((unused))
int64_t nn_requantize(int32_t val, int32_t multiplier, int32_t shift)
{
    return nn_divide_by_power_of_two(
               nn_doubling_high_mult_no_sat(val, multiplier),
               shift);
}

/* =========================================================================
 * clamp_i8
 *   Clamp an int32/int64 value into the int8 range [lo, hi].
 * ========================================================================= */
static inline int8_t clamp_i8(int32_t x, int32_t lo, int32_t hi)
{
    if (x < lo) return (int8_t)lo;
    if (x > hi) return (int8_t)hi;
    return (int8_t)x;
}

/* =========================================================================
 * cmodel_activation_clamp_asym8
 *
 *   Elementwise clamp of an asym8 tensor to [activation_min, activation_max].
 *   This primitive covers:
 *     ReLU   : activation_min = quantized(0), activation_max = 127
 *     ReLU6  : activation_min = quantized(0), activation_max = quantized(6)
 *     Clamp  : arbitrary int8 bounds
 *
 *   The operation is:
 *     out[i] = clamp(inp[i], activation_min, activation_max)
 *
 *   No requantization is performed.  Input and output are on the same
 *   quantization scale (this is the canonical NNLib asym8->asym8 activation
 *   convention for same-scale tensors).
 * ========================================================================= */
void cmodel_activation_clamp_asym8(
    int8_t       * __restrict__ p_out,
    const int8_t * __restrict__ p_inp,
    int num_elements,
    int activation_min,
    int activation_max)
{
    for (int i = 0; i < num_elements; i++) {
        p_out[i] = clamp_i8((int32_t)p_inp[i], activation_min, activation_max);
    }
}
